### ISSUE TITLE
rishka_double_to_long and rishka_long_to_double could probably disappear

### ISSUE THREAD

**Issue by robertlipe** [nthnn/rishka#2]
https://github.com/nthnn/rishka/blob/6a92ab62954f06c21db48c3e19ba9c5014d7c4e0/src/rishka_util.cpp#L20

You could probably make these specializations of an overload and really help the optimizer just pull these inline without the overhead of a function call. You're seemingly using type punning here to make your deal with the optimizer clear and keep alignment, etc. OK (a lovely approach!) but making it an overloaded operator, you really could make this a zero-cost abstraction.

For some reason, code of this type (including my own) always tends to look more like C with a salting of C++ that sometimes forgets to take advantage of all the things that C++ can offer. Don't forget about things like constexpr and overloads that can really help the readability to both you and teh optimizer.

These might even reduce to a lowly cast if you have control of the memory layout of both the input and outut here...

**Comment by nthnn** [comment]
I can't use `constexpr` with `rishka_double_to_long()` and `rishka_long_to_double()` since the function body is not a `return` statement. So, I tried making `rishka_double_to_long()` into an `inline` function, and its actually almost twice much faster than the non-`inline` version.

![Test](https://github.com/nthnn/rishka/assets/90981832/004690bf-70bf-4832-b419-c92ec49d10b3)

The first conversion is the non-`inline` which took 116 milliseconds, while the second one is the `inline` version and only took 67 milliseconds. For the sake of additional context, here's the code I used to test it out:

```cpp
typedef void (*CbFunc)();

void execute_timer(CbFunc callback) {
    unsigned long start = micros();
    callback();

    double elapsed_time = micros() - start;
    Serial.print("Time elapsed: ");
    Serial.print(elapsed_time, 6);
    Serial.println(" milliseconds");
}

int64_t rishka_double_to_long_1(double d) {
    union { double input; int64_t output; } data;
    data.input = d;
    return data.output;
}

inline int64_t rishka_double_to_long_2(double d) {
    union { double input; int64_t output; } data;
    data.input = d;
    return data.output;
}

void setup() {
    Serial.begin(115200);
    execute_timer([]() {
        Serial.print("Converted: ");
        Serial.println(rishka_double_to_long_1(3.14159));
    });
    execute_timer([]() {
        Serial.print("Converted: ");
        Serial.println(rishka_double_to_long_2(3.14159));
    });
}

void loop() { vTaskDelay(10); }
```

---

> ... always tends to look more like C with a salting of C++ that sometimes forgets to take advantage of all the things that C++ can offer.

That's actually what I'm working with my current programming style. I'll go keep that in mind. Thank you!

**Comment by nthnn** [comment]
I also used `inline` with VM helper functions with this latest commit. The VM got much faster now.

**Comment by robertlipe** [comment]
Nice.
